# Generated by Django 3.0 on 2019-12-14 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentCasualty',
            fields=[
                ('accident', models.OneToOneField(db_column='Accident_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='client.Accidents')),
            ],
            options={
                'db_table': 'accident_casualty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccidentDate',
            fields=[
                ('accident', models.OneToOneField(db_column='Accident_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='client.Accidents')),
            ],
            options={
                'db_table': 'accident_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccidentLocation',
            fields=[
                ('accident', models.OneToOneField(db_column='Accident_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='client.Accidents')),
            ],
            options={
                'db_table': 'accident_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccidentVehicle',
            fields=[
                ('accident', models.OneToOneField(db_column='Accident_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='client.Accidents')),
            ],
            options={
                'db_table': 'accident_vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(blank=True, db_column='Day_of_Week', max_length=9, null=True)),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('urban_or_rural_area', models.CharField(blank=True, db_column='Urban_or_Rural_Area', max_length=11, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(blank=True, db_column='Vehicle_Type', max_length=37, null=True)),
                ('was_vehicle_left_hand_driver', models.IntegerField(blank=True, db_column='Was_Vehicle_Left_Hand_Driver', null=True)),
                ('age_of_vehicle', models.IntegerField(blank=True, db_column='Age_of_Vehicle', null=True)),
                ('vehicle_manoeuvre', models.CharField(blank=True, db_column='Vehicle_Manoeuvre', max_length=35, null=True)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.CreateModel(
            name='LocationDate',
            fields=[
                ('location', models.OneToOneField(db_column='Location_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='client.Location')),
            ],
            options={
                'db_table': 'location_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleCasualty',
            fields=[
                ('vehicle', models.OneToOneField(db_column='Vehicle_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='client.Vehicles')),
            ],
            options={
                'db_table': 'vehicle_casualty',
                'managed': False,
            },
        ),
    ]
